name: Backend CI

# Hvornår workflowet skal køre
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Midlertidig linux-computer i skyen der bygge og teste mit projekt
  build-and-test:
    runs-on: ubuntu-22.04

    # sørg for at alt sker i backend-mappen. Alle scripts kører fx i bavkend. Behøver ik skrive cd backend hele tiden
    defaults:
      run:
        working-directory: backend

    # Hvad min ci skal gøres i denne rækkefølge
    steps:
      # Downloader min kode fra GitHub til den virtuelle maskine
      - name: Checkout code
        # færdiglavede moduler fra gitactions -> Kan bruges til at gøre almindelige ting nemt og hurtigt, og svarer lidt til plugnins
        uses: actions/checkout@v3

        # Installerer node version 20 som matcher min lokale udvikling
      - name: Setup Node.js

        uses: actions/setup-node@v3
        with:
          node-version: 20

        # Installerer mine dependencies. npm ci er hurtigere end npm install
      - name: Install dependencies
        run: npm ci

        # tjekker min ts kode for fejl og "dårlig stil"
      - name: Lint code
        run: npx eslint . --ext .ts

        # Fix de linting fejl som automatisk kan fikses fx anførselstegn og identation
      - name: Run ESLint with auto-fix
        run: npm run lint

        # Kører mine tests og laver code coverage rapport
      - name: Run tests with coverage
        #   kommer fra min package.json:"test:ci": "jest --coverage --watchAll=false"
        #Kør tets én gang --watchAll=false
        #Lav en coverage rapport med data over hvor meget af koden der er testet
        run: npm run test:ci
